defaults: &defaults
  title: Stat Patient
  url: http://wwwstat-prod.com

development:
  <<: *defaults
  url: http://localhost:3000

test:
  <<: *defaults
  url: http://localhost:3000

production:
  <<: *defaults
  url: http://www.statqa.com
